# Generated by Django 4.1.3 on 2023-05-15 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import typing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[
                 ('T', 'Transaction'), ('B', 'Budgeting')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('id_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                 primary_key=True, related_name='of_account', serialize=False, to='budget.id')),
            ],
            options={
                'abstract': False,
            },
            bases=('budget.id',),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                 primary_key=True, related_name='of_budget', serialize=False, to='budget.id')),
                ('name', models.CharField(max_length=100)),
                ('budget_of', models.OneToOneField(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('budget.id',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('id_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                 primary_key=True, related_name='of_category', serialize=False, to='budget.id')),
                ('budget', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=('budget.id',),
        ),
        migrations.CreateModel(
            name='CategoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)ss', to='budget.transaction')),
                ('sink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='sink_entries', to='budget.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='source_entries', to='budget.category')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CategoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)ss', to='budget.transaction')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='notes', to='budget.category')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('from_budget', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
                ('to_budget', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.budget')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='friends',
            field=models.ManyToManyField(
                blank=True, through='budget.BudgetFriends', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budget',
            name='payee_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='payee_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)ss', to='budget.transaction')),
                ('sink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='sink_entries', to='budget.account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='source_entries', to='budget.account')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AccountNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)ss', to='budget.transaction')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='notes', to='budget.account')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.AddConstraint(
            model_name='categorypart',
            constraint=models.UniqueConstraint(
                fields=('transaction', 'source', 'sink'), name='m2m_categorypart'),
        ),
        migrations.AddConstraint(
            model_name='categorynote',
            constraint=models.UniqueConstraint(
                fields=('transaction', 'account', 'user'), name='m2m_categorynote'),
        ),
        migrations.AddConstraint(
            model_name='budgetfriends',
            constraint=models.UniqueConstraint(
                fields=('from_budget', 'to_budget'), name='m2m_budgetfriends'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('budget_of__isnull', True), (
                'payee_of__isnull', True), _connector='OR'), name='cant_be_payee_and_budget'),
        ),
        migrations.AddConstraint(
            model_name='accountpart',
            constraint=models.UniqueConstraint(
                fields=('transaction', 'source', 'sink'), name='m2m_accountpart'),
        ),
        migrations.AddConstraint(
            model_name='accountnote',
            constraint=models.UniqueConstraint(
                fields=('transaction', 'account', 'user'), name='m2m_accountnote'),
        ),
    ]
