# Generated by Django 4.1.3 on 2022-11-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionAccountPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='accounts',
            field=models.ManyToManyField(through='budget.TransactionAccountPart', to='budget.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(through='budget.TransactionCategoryPart', to='budget.category'),
        ),
        migrations.AddField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.AddConstraint(
            model_name='transactioncategorypart',
            constraint=models.UniqueConstraint(fields=('transaction', 'to'), name='m2m_transactioncategorypart'),
        ),
        migrations.AddConstraint(
            model_name='transactionaccountpart',
            constraint=models.UniqueConstraint(fields=('transaction', 'to'), name='m2m_transactionaccountpart'),
        ),
    ]
