# Generated by Django 4.1.3 on 2023-06-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='initial_currency',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
