# Generated by Django 4.1.3 on 2022-11-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='transactionaccountpart',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='transactionaccountpart',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_parts', to='budget.transaction'),
        ),
        migrations.AlterField(
            model_name='transactioncategorypart',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='transactioncategorypart',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_parts', to='budget.transaction'),
        ),
    ]
