# Generated by Django 4.2.2 on 2023-06-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_initial_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accounts',
            field=models.ManyToManyField(through='budget.AccountPart', to='budget.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(through='budget.CategoryPart', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accountpart',
            name='sink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='categorypart',
            name='sink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='budget.category'),
        ),
    ]
