# Generated by Django 4.1.3 on 2023-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_group_account_order_category_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
