# Generated by Django 4.2.2 on 2023-07-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_transaction_accounts_transaction_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel('AccountPart', 'AccountEntry'),
        migrations.RenameModel('CategoryPart', 'CategoryEntry'),
        migrations.AlterModelOptions(
            name='accountentry',
            options={'verbose_name_plural': 'accountentries'},
        ),
        migrations.AlterModelOptions(
            name='categoryentry',
            options={'verbose_name_plural': 'categoryentries'},
        ),
        migrations.RemoveConstraint(
            model_name='accountentry',
            name='m2m_accountpart',
        ),
        migrations.RemoveConstraint(
            model_name='categoryentry',
            name='m2m_categorypart',
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='budget.transaction'),
        ),
        migrations.AlterField(
            model_name='categoryentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='budget.transaction'),
        ),
    ]
