# Generated by Django 4.2.2 on 2023-07-07 17:50

from django.db import migrations, models
import django.db.models.deletion
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
import datetime


def copy_fields(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Transaction = apps.get_model("budget", "Transaction")
    TransactionPart = apps.get_model("budget", "TransactionPart")
    parts = list(TransactionPart.objects.all())
    transactions = Transaction.objects.bulk_create([
        Transaction(date=part.date, kind=part.kind)
        for part in parts
    ])
    for part, transaction in zip(parts, transactions):
        part.transaction = transaction
    TransactionPart.objects.bulk_update(parts, ['transaction'])


def copy_fields_rev(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Transaction = apps.get_model("budget", "Transaction")
    TransactionPart = apps.get_model("budget", "TransactionPart")
    parts = list(TransactionPart.objects.select_related('transaction'))
    for part in parts:
        part.date = part.transaction.date
        part.kind = part.transaction.kind
    TransactionPart.objects.bulk_update(parts, ['date', 'kind'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_parts_to_entries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionPart',
        ),
        migrations.RenameField(
            model_name='accountentry',
            old_name='transaction',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='categoryentry',
            old_name='transaction',
            new_name='part',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[
                 ('T', 'Transaction'), ('B', 'Budgeting')], default='T', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='transactionpart',
            name='transaction',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.transaction', related_name="parts"),
        ),
        migrations.RunPython(copy_fields, copy_fields_rev),
        migrations.AlterField(
            model_name='transactionpart',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='parts', to='budget.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(model_name='transactionpart', name='date',
                              field=models.DateField(
                                  default=datetime.date.today),
                              preserve_default=True),
        migrations.RemoveField(
            model_name='transactionpart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transactionpart',
            name='kind',
        ),
    ]
