# Generated by Django 4.1.3 on 2023-04-05 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_transaction_kind_alter_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='budgetuser',
            name='friends',
            field=models.ManyToManyField(to='budget.budgetuser'),
        ),
        migrations.AddField(
            model_name='budgetuser',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_of',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.budgetuser'),
        ),
        migrations.AddField(
            model_name='budget',
            name='payee_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='payee_set', to='budget.budgetuser'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('budget_of__isnull', True), (
                'payee_of__isnull', True), _connector='OR'), name='cant_be_payee_and_budget'),
        ),
    ]
