# Generated by Django 4.1.3 on 2023-04-06 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0005_budgetuser_remove_budget_owner_remove_budget_writers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='friends',
            field=models.ManyToManyField(blank=True, to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='payee_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payee_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BudgetUser',
        ),
    ]
