# Generated by Django 4.2.2 on 2023-07-11 05:43

from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from itertools import chain


def merge_notes(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    TransactionPart = apps.get_model("budget", "TransactionPart")
    parts = (TransactionPart.objects
             .prefetch_related('accountnotes', 'categorynotes'))
    for part in parts:
        part.note = ', '.join({
            note.note
            for note in chain(part.accountnotes.all(),
                              part.categorynotes.all())
            if note.note})
    TransactionPart.objects.bulk_update(parts, ['note'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_split_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpart',
            name='note',
            field=models.TextField(default='', blank=True, max_length=1000),
            preserve_default=False,
        ),
        migrations.RunPython(merge_notes),
        migrations.DeleteModel(
            name='AccountNote',
        ),
        migrations.DeleteModel(
            name='CategoryNote',
        ),
    ]
