# Generated by Django 4.1.3 on 2023-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budget_friends_alter_budget_budget_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='category',
            name='currency',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
