# Generated by Django 4.2.3 on 2023-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_transactionpart_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='initial_split',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
