# Generated by Django 4.2.3 on 2023-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budget_initial_split'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('budget', 'name', 'currency'), name='m2m_account'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('budget', 'name', 'currency'), name='m2m_category'),
        ),
    ]
