# Generated by Django 4.2.3 on 2023-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_transaction_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clearable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cleared',
            field=models.ManyToManyField(related_name='cleared', to='budget.account'),
        ),
    ]
