# Generated by Django 4.2.3 on 2023-08-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_account_clearable_transaction_cleared'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.RenameField(
                'transaction', 'cleared', 'cleared_account'),
            migrations.CreateModel(
                name='Cleared',
                fields=[
                    ('id', models.BigAutoField(auto_created=True,
                                               primary_key=True, serialize=False, verbose_name='ID')),
                    ('account', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='budget.account', related_name='cleared')),
                    ('transaction', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='budget.transaction', related_name='cleared')),
                ],
                options={
                    'db_table': 'budget_transaction_cleared',
                    'unique_together': {('transaction', 'account')},
                },
            ),
            migrations.AlterField(
                model_name='transaction',
                name='cleared_account',
                field=models.ManyToManyField(
                    related_name='cleared_transaction', through='budget.Cleared', to='budget.account'),
            ),
        ])
    ]
