# Generated by Django 4.2.3 on 2023-08-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_transactioncleared_alter_transaction_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleared',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
