# Generated by Django 4.2.3 on 2024-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_cleared_reconciled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='budget',
            name='initial_currency',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='currency',
            field=models.CharField(max_length=16),
        ),
    ]
